{"uuid": "04d30468-d8a1-4400-9b99-6b1d338716ff", "children": ["5fd5db93-6e50-4dcb-8b86-e8be09a97ebc"], "befores": [{"name": "_xunit_setup_method_fixture_TestTestSenaryo5", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 877, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\python.py\", line 815, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\python.py\", line 709, in _call_with_optional_argument\n    func(arg)\n  File \"c:\\Users\\Ömer Vardar\\Desktop\\TobetoAutomatedTesting\\test_testsenaryo5.py\", line 17, in setup_method\n    self.login(\"furkangmsky@gmail.com\", \"Furkan-1445\")\n  File \"c:\\Users\\Ömer Vardar\\Desktop\\TobetoAutomatedTesting\\test_testsenaryo5.py\", line 40, in login\n    WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH, \"//button[@type='submit']\"))).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ömer Vardar\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1719650988275, "stop": 1719651019528}], "start": 1719650988275, "stop": 1719651019674}